### ISSUE TITLE
Using that with framework7 lib

### ISSUE THREAD

**Issue by mbajur** [lmk123/vue-framework7#5]
Hello,
i've been thinking - do you guys think that would be possible to use vue-framework7 along with framework7 lib directly?

To be honest, i don't need framework7 lib for anything cause i can achieve all i want using vue-framework7...apart from material design goodies. Including material css file instead of ios one is not enough, i need to somehow emulate the `new Vue({material: true})` behaviour.

It would be great to be able to use `material: true` without the whole fw7 lib but i doubt vue-fw7 provides such functionality. If there is such option, please just let me know, i will be more than happy to be wrong on this one :D 

Thanks in advance!

**Comment by lmk123** [comment]
vue-framework7 don't depend on framwork7 lib, it only need framework7 css file ([iOS style](http://framework7.io/dist/css/framework7.ios.min.css) or [material style](http://framework7.io/dist/css/framework7.material.min.css)). There isn't a `material: true` option, you have to use material style instead of iOS style.
